- name: "Aguardando conexão..."
  hosts: rockylinux8
  gather_facts: True

  tasks:
    - name: Criando o arquivo {{ ID_SQL }}.sql
      ansible.builtin.file:
        path: /home/ansible/{{ ID_SQL }}.sql
        state: touch

    - name: Enviando código SQL para o arquivo {{ ID_SQL }}.sql
      ansible.builtin.blockinfile:
        path: /home/ansible/{{ ID_SQL }}.sql
        block: |
          {{ SQL }}
        